oot = "."
tmp_dir = ".docker_build"

[build]
pre_cmd = ["go run ./cmd/gen_translator_keys/"]
cmd = "go build -o .docker_build/bot ./cmd/bot"
bin = "bot"
full_bin = ".docker_build/bot"
include_ext = ["go", "json"]
exclude = ["internal/translator/keys.go"]
exclude_regex = ["_gen\\.go"]

[log]
time = true

[run]
cmd = ".docker_build/bot"