oot = "."
tmp_dir = ".docker_build"

[build]
cmd = "go build -o .docker_build/bot ./cmd/bot"
bin = "bot"
full_bin = ".docker_build/bot"
include_ext = ["go", "json"]

[log]
time = true

[run]
cmd = ".docker_build/bot"